# Generated by Django 5.0.7 on 2024-07-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата/время')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('house', models.CharField(max_length=50, verbose_name='дом')),
                ('flat', models.CharField(max_length=50, verbose_name='квартира')),
                ('text', models.TextField(max_length=250, verbose_name='текст заявки')),
                ('period_of_execution', models.CharField(max_length=50, verbose_name='срок исполнения')),
                ('FIO', models.CharField(max_length=50, verbose_name='ФИО заявителя')),
                ('telephone_number', models.CharField(max_length=50, verbose_name='телефон')),
            ],
        ),
    ]
