# Generated by Django 5.0.7 on 2024-07-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_of_applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('house', models.CharField(max_length=50, verbose_name='дом')),
                ('flat', models.CharField(max_length=50, verbose_name='квартира')),
                ('text', models.TextField(max_length=250, verbose_name='текст заявки')),
                ('period_of_execution', models.CharField(max_length=50, verbose_name='срок исполнения')),
                ('FIO', models.CharField(max_length=50, verbose_name='ФИО заявителя')),
                ('telephone_number', models.CharField(max_length=50, verbose_name='телефон')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
