# Generated by Django 5.0.7 on 2024-07-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_list_of_applications_delete_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_of_applications',
            name='priority',
            field=models.CharField(choices=[('low', 'Текущая'), ('medium', 'Коммерческая'), ('high', 'Аварийная')], default='low', max_length=10, verbose_name='Приоритет'),
        ),
    ]
