# Generated by Django 5.0.7 on 2024-07-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_list_of_applications_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_of_applications',
            name='priority',
            field=models.CharField(choices=[('Текущая', 'Текущая'), ('Коммерческая', 'Коммерческая'), ('Аварийная', 'Аварийная'), ('Плановая', 'Плановая'), ('Дежурная', 'Дежурная')], default='Текущая', max_length=12, verbose_name='Приоритет'),
        ),
    ]
