# Generated by Django 5.0.7 on 2024-08-13 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_request', '0002_alter_articles_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 13, 8, 24, 10, 307189), verbose_name='Дата/время'),
        ),
    ]
