# Generated by Django 5.0.7 on 2024-08-13 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_request', '0004_alter_articles_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='comment',
            field=models.CharField(max_length=50, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 13, 16, 7, 35, 716426), verbose_name='Дата/время'),
        ),
    ]
