# Generated by Django 5.0.7 on 2024-08-13 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_request', '0005_articles_comment_alter_articles_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='comment',
            field=models.CharField(default=0, max_length=50, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 13, 16, 34, 49, 513083), verbose_name='Дата/время'),
        ),
    ]
